spring.datasource.url=jdbc:mysql://localhost:3306/seydoumicroservicesdemo
spring.datasource.username=blabla
spring.datasource.password=tata
spring.application.name=demoEmployee
server.port=8080
# Set Your Context Path Here
server.servlet.context-path=/demoemployee

## seydoumicroservicesdemo